/**
 * Detox configuration for the Eaz Community mobile app.
 *
 * Android is the primary target (emulator). iOS simulator config is included
 * but requires `npx pod-install` (the ios/ workspace is generated by CocoaPods).
 *
 * Before running, set the device identifiers below to ones that exist locally:
 *   - Android: `emulator -list-avds` → put the AVD name in devices.emulator.device.avdName
 *   - iOS:     `xcrun simctl list devicetypes` → adjust devices.simulator.device.type
 *
 * Usage:
 *   pnpm --filter @eaz-community/frontend e2e:build:android
 *   pnpm --filter @eaz-community/frontend e2e:test:android
 *
 * @type {Detox.DetoxConfig}
 */
module.exports = {
  testRunner: {
    args: {
      config: 'e2e/jest.config.js',
      _: ['e2e'],
    },
    jest: {
      setupTimeout: 120000,
    },
  },
  apps: {
    'android.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      testBinaryPath: 'android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
      build:
        'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..',
      reversePorts: [8081],
    },
    'android.release': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/release/app-release.apk',
      testBinaryPath:
        'android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk',
      build:
        'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..',
    },
    'ios.debug': {
      type: 'ios.app',
      binaryPath: 'ios/build/Build/Products/Debug-iphonesimulator/EazCommunity.app',
      build:
        'xcodebuild -workspace ios/EazCommunity.xcworkspace -scheme EazCommunity -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'ios.release': {
      type: 'ios.app',
      binaryPath: 'ios/build/Build/Products/Release-iphonesimulator/EazCommunity.app',
      build:
        'xcodebuild -workspace ios/EazCommunity.xcworkspace -scheme EazCommunity -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
    },
  },
  devices: {
    emulator: {
      type: 'android.emulator',
      device: {
        // Change to a local AVD name from `emulator -list-avds`.
        avdName: 'Pixel_7_API_34',
      },
    },
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 15',
      },
    },
  },
  configurations: {
    'android.emu.debug': {
      device: 'emulator',
      app: 'android.debug',
    },
    'android.emu.release': {
      device: 'emulator',
      app: 'android.release',
    },
    'ios.sim.debug': {
      device: 'simulator',
      app: 'ios.debug',
    },
    'ios.sim.release': {
      device: 'simulator',
      app: 'ios.release',
    },
  },
};
